#!/usr/bin/env python

import argparse
import atexit
import os
import pathlib
import platform
import pylmadb
import re
import shutil
import tempfile

from prompt_toolkit import prompt
from prompt_toolkit.history import InMemoryHistory

def handle_meta_command(conn, command, args):
    if command == 'tables':
        for table in conn.list_tables():
            print(table)
    elif command == 'schema':
        if len(args) != 1:
            # TODO: make this a UsageError
            raise RuntimeError('wrong arguments.')

        for column, ty in conn.describe_table(args[0]):
            print(column, ty)
    else:
        raise RuntimeError('unknown meta command .{}'.format(command))

def handle_command(conn, command):
    try:
        if command.startswith('.'):
            args = command.partition('\n')[0].split(' ')
            handle_meta_command(conn, command=args[0][1:], args=args[1:])
        else:
            stmt = conn.prepare(command)
            for row in stmt:
                print(row)
    # TODO: this should be our own error type.
    except RuntimeError as e:
        print('Error: {}'.format(e))

parser = argparse.ArgumentParser(description='LMADB command line client.')
parser.add_argument('path', type=str, nargs='?', help='path to database')
parser.add_argument('-s', '--script', help='SQL script to process')

args = parser.parse_args()

print('LMADB version {}, Python version {}'.format(pylmadb.__version__, platform.python_version()))

if args.path is None:
    # create a temporary database that is destroyed on exit.
    tmpdir = tempfile.mkdtemp()
    atexit.register(lambda: shutil.rmtree(tmpdir))

    args.path = os.path.join(tmpdir, 'lmadb')
    print('Connected to a transient database: {}'.format(args.path))

conn = pylmadb.connection(args.path)

if args.script:
    # load script into memory, strip out all comments and then process each command
    sql = pathlib.Path(args.script).read_text()
    # TODO: this won't work for semicolons in quoted strings.
    sql = re.sub(';.*\n', ';', sql)

    for command in (e.strip() for e in sql.split(';')):
        # skip empty lines.
        if command:
            handle_command(conn, command)
else:
    history = InMemoryHistory()

    while True:
        # TODO: make this accept multiline interactive input.
        command = prompt('> ', history=history)
        if len(command) == 0:
            continue

        if command == 'quit' or command == 'q':
            break

        handle_command(conn, command)
